name: nightcore_to_youtube
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.11
  - aiosignal=1.3.2
  - alsa-lib=1.2.13
  - aom=3.9.1
  - attr=2.5.1
  - attrs=25.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - cachetools=5.5.1
  - cairo=1.18.2
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - click=8.1.8
  - cryptography=44.0.0
  - dav1d=1.2.1
  - dbus=1.13.6
  - expat=2.6.4
  - ffmpeg=7.1.0
  - ffmpeg-python=0.2.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.5.0
  - future=1.0.0
  - gdk-pixbuf=2.42.12
  - gettext=0.23.1
  - gettext-tools=0.23.1
  - gmp=6.3.0
  - google-auth=2.38.0
  - graphite2=1.3.13
  - h2=4.1.0
  - harfbuzz=10.2.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - lame=3.100
  - lcms2=2.17
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - level-zero=1.20.5
  - libabseil=20240722.0
  - libasprintf=0.23.1
  - libasprintf-devel=0.23.1
  - libass=0.17.3
  - libcap=2.71
  - libdeflate=1.23
  - libdrm=2.4.124
  - libegl=1.7.0
  - libexpat=2.6.4
  - libffi=3.4.2
  - libflac=1.4.3
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgcrypt-lib=1.11.0
  - libgettextpo=0.23.1
  - libgettextpo-devel=0.23.1
  - libgl=1.7.0
  - libglib=2.82.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=14.2.0
  - libgpg-error=1.51
  - libhwloc=2.11.2
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblzma=5.6.4
  - libnsl=2.0.1
  - libogg=1.3.5
  - libopenvino=2025.0.0
  - libopenvino-auto-batch-plugin=2025.0.0
  - libopenvino-auto-plugin=2025.0.0
  - libopenvino-hetero-plugin=2025.0.0
  - libopenvino-intel-cpu-plugin=2025.0.0
  - libopenvino-intel-gpu-plugin=2025.0.0
  - libopenvino-intel-npu-plugin=2025.0.0
  - libopenvino-ir-frontend=2025.0.0
  - libopenvino-onnx-frontend=2025.0.0
  - libopenvino-paddle-frontend=2025.0.0
  - libopenvino-pytorch-frontend=2025.0.0
  - libopenvino-tensorflow-frontend=2025.0.0
  - libopenvino-tensorflow-lite-frontend=2025.0.0
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.46
  - libprotobuf=5.28.3
  - librsvg=2.58.4
  - libsndfile=1.2.2
  - libsqlite=3.48.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libsystemd0=257.3
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libva=2.22.0
  - libvorbis=1.3.7
  - libvpx=1.14.1
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.13.5
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - mpg123=1.32.9
  - multidict=6.1.0
  - ncurses=6.5
  - ocl-icd=2.3.2
  - opencl-headers=2024.10.24
  - openh264=2.6.0
  - openjpeg=2.5.3
  - openssl=3.4.1
  - pango=1.56.1
  - pcre2=10.44
  - pillow=11.1.0
  - pip=25.0
  - pixman=0.44.2
  - propcache=0.2.1
  - pthread-stubs=0.4
  - pugixml=1.15
  - pulseaudio-client=17.0
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.1
  - pycparser=2.22
  - pyopenssl=25.0.0
  - pysocks=1.7.1
  - python=3.11.11
  - python_abi=3.11
  - pyu2f=0.1.5
  - readline=8.2
  - requests=2.32.3
  - rsa=4.9
  - sdl2=2.30.10
  - setuptools=75.8.0
  - six=1.17.0
  - snappy=1.2.1
  - svt-av1=2.3.0
  - tbb=2022.0.0
  - tk=8.6.13
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - urllib3=2.3.0
  - wayland=1.23.1
  - wayland-protocols=1.40
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.5
  - xorg-libx11=1.8.11
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxrender=0.9.12
  - yarl=1.18.3
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - greenlet==3.1.1
      - playwright==1.49.1
      - pyee==12.0.0
