import re

AUDIO_EXTENSIONS = ['mp3', 'opus']
COVER_EXTENSIONS = ['png', 'jpg']
VIDEO_EXTENSIONS = ['mp4']

SPEED_REVERB_NAME_SEPARATOR = '_'
NIGHTCORE_NAME_PATTERN = re.compile(rf'\d+(?:{SPEED_REVERB_NAME_SEPARATOR}\d+)?')

MIN_VIDEO_RATIO = 16 / 9
MAX_VIDEO_RATIO = 32 / 9
